services:

  backend:
    build:
      context: ../cycop1/backend
      dockerfile: Dockerfile
    container_name: analytic-web-backend
    environment:
      API_PATH: https://defnex-api.please-scan.com
      API_AUTHEN_PASSWORD: v5QQY1WXhrV8
      ORG_ID: default
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ../cycop1/frontend
      dockerfile: Dockerfile
    container_name: analytic-web-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_TARGET=http://backend:8000
